package com.sypark.openTicket


const val FILENAME = "com.sypark.openTicket"


const val PREFERENCE_SORT_INDEX = "SORT_INDEX"
const val PREFERENCE_KEY_FILTER_AREA = "FILTER_AREA"
const val PREFERENCE_KEY_EMAIL = "EMAIL"
const val PREFERENCE_KEY_PW = "PW"
const val PREFERENCE_KEY_ = "PW"

const val PREFERENCE_KEY_GRANT_TYPE = "GRANT_TYPE"
const val PREFERENCE_KEY_ACCESS_TOKEN = "ACCESS_TOKEN"
const val PREFERENCE_KEY_REFRESH_TOKEN = "REFRESH_TOKEN"
